# Generated by Django 5.2.2 on 2025-06-09 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Manual')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción General')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to='manuals.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manuales',
                'db_table': 'manuales',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Procedimiento')),
                ('content', models.TextField(verbose_name='Contenido del Procedimiento')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Versión')),
                ('last_reviewed', models.DateField(default=django.utils.timezone.now, verbose_name='Última Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='manuals.manual', verbose_name='Manual Asociado')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'procedimientos',
                'ordering': ['manual__title', 'title', '-version'],
                'unique_together': {('manual', 'title', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del documento (constante a través de versiones)', max_length=255)),
                ('file', models.FileField(upload_to='document_files/')),
                ('description', models.CharField(blank=True, help_text='Descripción de esta versión específica', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('previous_version', models.OneToOneField(blank=True, help_text='Versión anterior en el historial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='manuals.documentfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_files', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='manuals.procedure')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'db_table': 'bytefiles',
                'ordering': ['-version_number', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil del Usuario',
                'verbose_name_plural': 'Perfiles de los Usuarios',
                'db_table': 'profile',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
