# Generated by Django 5.2.2 on 2025-06-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categorias',
        ),
    ]
